version: '3'

services:
  docs:
    image: synck_local_docs
    container_name: synck_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./synck:/app/synck:z
    ports:
      - '9000:9000'
    command: /start-docs
